name: Bundle
on:
  push:
    branches: [ master ]
  tags:  
    - v*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - name: Install
        run: npm install

      - name: Create dist folder
        run: mkdir dist

      - name: Build
        run: npm run build

      - name: Bundle
        run: npm run bundle

      - name: Create dist folder
        run: ls dist

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            dist/*.tar.gz
